name: Check Salesforce Encryption Scheme Changes

on:
  pull_request:
    # paths:
    #   - "classes/*.cls" # Adjust path based on your repo structure
    branches:
      - main
      # - "feature/**"

jobs:
  check-naming-convention:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

          # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to
          # improve performance
          fetch-depth: 0

      - name: Verify Apex class naming convention
        id: apex_check
        run: |
          INVALID_FILE=()
          APEX_CLS_NAME_CHECK="Passed!"

          REGEX_PATTERNS=( 
                      "^A3A_[A-Za-z]+Testing\.cls$"
                      "^ABC_[A-Za-z]+Service\.cls"
                      "^A3C_[A-Za-z]+Service\.cls$"
                    )
          FILES_CHANGED=($(git diff --name-only --diff-filter=AM origin/main...HEAD -- '*.cls' | xargs -I {} basename {}))

          echo "Found following .cls files with change \n $FILES_CHANGED"''

          if [ ${#FILES_CHANGED[@]} -eq 0 ]; then
              echo "No .cls files found with changes"
              INVALID_FILE="None!"
              exit 0
          fi

          for FILE_NAME in ${FILES_CHANGED[@]}; do
              echo "Verifying if $FILE_NAME is following Aapex class naming convention..."

              for PATTERN in ${REGEX_PATTERNS[@]}; do
                  if [[ $FILE_NAME =~ $PATTERN ]]; then
                    matched=true
                    break
                  else
                    matched=false
                  fi
              done

              if [ "$matched" = true ]; then
                  echo "$FILE_NAME passed naming convention"
              else
                  INVALID_FILES+=("$FILE_NAME")
                  echo "$FILE_NAME has not passed naming convention check!"
              fi
          done

          if [ ${#INVALID_FILES[@]} -eq 0 ]; then
              echo "Changes are valid!"
              INVALID_FILES=None!
          else
              echo "Invalid File names found!"
              echo "INVALID_FILES : $INVALID_FILES"
              APEX_CLS_NAME_CHECK="Failed!"
          fi

          echo "INVALID_FILES=$INVALID_FILES" >> $GITHUB_OUTPUT
          echo "APEX_CLS_NAME_CHECK=$APEX_CLS_NAME_CHECK" >> $GITHUB_OUTPUT


      - name: Post Apex class naming convention as a PR comment
        if: success() || failure()  # This ensures the step runs even if a previous step fails
        uses: peter-evans/create-or-update-comment@v4 #pinv4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            *Apex Class Naming Convention Check*
            - *Status*: ${{ steps.apex_check.outputs.APEX_CLS_NAME_CHECK }}
            - Invalid Files: ${{ steps.apex_check.outputs.INVALID_FILES }}
          reactions: "+1"
          comment-id: "APEX_CLS_NAME_CHECK"